import type { Metadata, Viewport } from 'next';
import {
    NextAuthProvider,
    NuqsProvider,
    QueryClientProvider,
    ThemeProvider,
} from './_providers';

import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    width: 'device-width',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <QueryClientProvider>
                    <ThemeProvider attribute="class" defaultTheme="system">
                        <NextAuthProvider>
                            <NuqsProvider>{children}</NuqsProvider>
                        </NextAuthProvider>
                    </ThemeProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
